#pragma once
#include <ice/forwards.hxx>

namespace ice::output
{


    //! \brief Describes a class which is capable of serializing a generated ICE AST.
    class Serializer
    {
    public:
        virtual ~Serializer() noexcept = default;

        //! \brief Output header file.
        //! \note This file is generated by default.
        virtual auto header_file() noexcept -> ice::output::ASTRoot& = 0;

        //! \brief Output source file.
        //! \note This file is generated by default.
        virtual auto source_file() noexcept -> ice::output::ASTRoot& = 0;

        //! \brief Output inline file.
        //! \note This file needs to be enabled for generation.
        virtual auto inline_file() noexcept -> ice::output::ASTRoot& = 0;
    };


} // namespace ice::output
