name: Nightly

on:
  schedule:
    # Every day at 1 am
    - cron: 0 1 * * *

jobs:
  nightly-build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup repository
      run: |
        pip install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Build (ReleaseDebug)
      run: |
        ice build
    - name: Verify
      run: |
        echo Nothing to verify yet
